apiVersion: tyk.tyk.io/v1alpha1
kind: APIDescription
metadata:
  name: sample-api-description-testapi50
spec:
  name: "sample API description testapi50"
  show: true
  auth_type: authToken
  policyRef:
    name: testapi50
    namespace: ksandbox-1
  docs:
    documentation: "http://httpbin.org/spec.json"
    doc_type: swagger_custom_url
  contextRef:
    name: local-operator-context
    namespace: ksandbox-1
